//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.26 at 04:29:37 PM CEST 
//

package org.w3c.unicorn.response;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import org.w3c.unicorn.util.LocalizedString;

/**
 * <p>
 * Java class for error element declaration.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;element name=&quot;error&quot;&gt;
 *   &lt;complexType&gt;
 *     &lt;complexContent&gt;
 *       &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref=&quot;{http://www.w3.org/unicorn/observationresponse}line&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;element ref=&quot;{http://www.w3.org/unicorn/observationresponse}column&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;element ref=&quot;{http://www.w3.org/unicorn/observationresponse}errortype&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;element ref=&quot;{http://www.w3.org/unicorn/observationresponse}context&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;element ref=&quot;{http://www.w3.org/unicorn/observationresponse}message&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *           &lt;element ref=&quot;{http://www.w3.org/unicorn/observationresponse}longmessage&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/restriction&gt;
 *     &lt;/complexContent&gt;
 *   &lt;/complexType&gt;
 * &lt;/element&gt;
 * </pre>
 * 
 * 
 */
public class Error {

	protected BigInteger line;

	protected BigInteger column;

	protected String errortype;

	protected String context;

	protected List<LocalizedString> message;

	protected List<Longmessage> longmessage;

	/**
	 * Gets the value of the line property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getLine() {
		return line;
	}

	/**
	 * Sets the value of the line property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setLine(BigInteger value) {
		this.line = value;
	}

	/**
	 * Gets the value of the column property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getColumn() {
		return column;
	}

	/**
	 * Sets the value of the column property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setColumn(BigInteger value) {
		this.column = value;
	}

	/**
	 * Gets the value of the errortype property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getErrortype() {
		return errortype;
	}

	/**
	 * Sets the value of the errortype property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setErrortype(String value) {
		this.errortype = value;
	}

	/**
	 * Gets the value of the context property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContext() {
		return context;
	}

	/**
	 * Sets the value of the context property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContext(String value) {
		this.context = value;
	}

	/**
	 * Gets the value of the message property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
	 * method for the message property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMessage().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<LocalizedString> getMessage() {
		if (message == null) {
			message = new ArrayList<LocalizedString>();
		}
		return this.message;
	}

	/**
	 * Gets the value of the longmessage property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
	 * method for the longmessage property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getLongmessage().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Longmessage }
	 * 
	 * 
	 */
	public List<Longmessage> getLongmessage() {
		if (longmessage == null) {
			longmessage = new ArrayList<Longmessage>();
		}
		return this.longmessage;
	}

	public void setMessage(List<LocalizedString> message) {
		this.message = message;
	}

	public void setLongmessage(List<Longmessage> longmessage) {
		this.longmessage = longmessage;
	}

}
