//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.26 at 04:29:37 PM CEST 
//


package org.w3c.unicorn.response;



/**
 * <p>Java class for code element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="code">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;extension base="{http://www.w3.org/unicorn/observationresponse}Inline">
 *       &lt;/extension>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
public class Code extends Inline
{
/*
	@Override
	public String toString() {
		return "<code>"+super.toString()+"</code>";
	}
*/
}
