//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.26 at 04:29:37 PM CEST 
//

package org.w3c.unicorn.response;

import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for Inline complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;Inline&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;choice maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
 *         &lt;element ref=&quot;{http://www.w3.org/unicorn/observationresponse}a&quot;/&gt;
 *         &lt;element ref=&quot;{http://www.w3.org/unicorn/observationresponse}img&quot;/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
public class Inline {

	protected List<Object> content = new ArrayList<Object>();

	/**
	 * Gets the value of the content property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
	 * method for the content property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link A }
	 * {@link String } {@link Img }
	 * 
	 * 
	 */
	public List<Object> getContent() {
		return this.content;
	}

	public void setContent(List<Object> content) {
		this.content = content;
	}
	/*
	 * @Override public String toString() { String res = ""; for (Object o :
	 * content) { res += o.toString(); } return res; }
	 */
}
