//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.26 at 04:29:37 PM CEST 
//

package org.w3c.unicorn.response;

import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for longmessage element declaration.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;element name=&quot;longmessage&quot;&gt;
 *   &lt;complexType&gt;
 *     &lt;complexContent&gt;
 *       &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *         &lt;sequence maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;&gt;
 *           &lt;element ref=&quot;{http://www.w3.org/unicorn/observationresponse}a&quot;/&gt;
 *           &lt;element ref=&quot;{http://www.w3.org/unicorn/observationresponse}code&quot;/&gt;
 *           &lt;element ref=&quot;{http://www.w3.org/unicorn/observationresponse}img&quot;/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/restriction&gt;
 *     &lt;/complexContent&gt;
 *   &lt;/complexType&gt;
 * &lt;/element&gt;
 * </pre>
 * 
 * 
 */
public class Longmessage {

	protected List<Object> content = new ArrayList<Object>();

	protected String lang;

	/**
	 * 
	 * @return The list of the contents.
	 */
	public List<Object> getContent() {
		if (content == null) {
			content = new ArrayList<Object>();
		}
		return this.content;
	}

	/**
	 * Sets the contents of the message.
	 * 
	 * @param content
	 *            The list to set.
	 */
	public void setContent(List<Object> content) {
		this.content = content;
	}

	/*
	 * @Override public String toString() { String res = ""; for (Object o :
	 * content) { res += o.toString(); } return res; }
	 */
	/**
	 * @return The language of the message.
	 */
	public String getLang() {
		return lang;
	}

	/**
	 * Sets the language for this message.
	 * 
	 * @param lang
	 *            The language of the message.
	 */
	public void setLang(String lang) {
		this.lang = lang;
	}

}
