//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.26 at 04:29:37 PM CEST 
//


package org.w3c.unicorn.response;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import org.w3c.unicorn.util.LocalizedString;


/**
 * <p>Java class for warning element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="warning">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{http://www.w3.org/unicorn/observationresponse}line" minOccurs="0"/>
 *           &lt;element ref="{http://www.w3.org/unicorn/observationresponse}column" minOccurs="0"/>
 *           &lt;element ref="{http://www.w3.org/unicorn/observationresponse}context" minOccurs="0"/>
 *           &lt;element ref="{http://www.w3.org/unicorn/observationresponse}level" minOccurs="0"/>
 *           &lt;element ref="{http://www.w3.org/unicorn/observationresponse}message" maxOccurs="unbounded"/>
 *           &lt;element ref="{http://www.w3.org/unicorn/observationresponse}longmessage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */

public class Warning {

    protected BigInteger line;
    protected BigInteger column;
    protected String context;
    protected Integer level;
    protected List<LocalizedString> message;
    protected List<Longmessage> longmessage;

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public BigInteger getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setLine(BigInteger value) {
        this.line = value;
    }

    /**
     * Gets the value of the column property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public BigInteger getColumn() {
        return column;
    }

    /**
     * Sets the value of the column property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setColumn(BigInteger value) {
        this.column = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContext(String value) {
        this.context = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setLevel(Integer value) {
        this.level = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<LocalizedString> getMessage() {
        if (message == null) {
            message = new ArrayList<LocalizedString>();
        }
        return this.message;
    }

    /**
     * Gets the value of the longmessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the longmessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLongmessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Longmessage }
     * 
     * 
     */
    public List<Longmessage> getLongmessage() {
        if (longmessage == null) {
            longmessage = new ArrayList<Longmessage>();
        }
        return this.longmessage;
    }

	public void setMessage(List<LocalizedString> message) {
		this.message = message;
	}

	public void setLongmessage(List<Longmessage> longmessage) {
		this.longmessage = longmessage;
	}

}
